

local JOKZ = loadstring(game:HttpGet('https://raw.githubusercontent.com/321312312321/databack/refs/heads/main/UISS'))()

local Window = JOKZ:CreateWindow({
   Name = "Script Made By JOKZ",
   Icon = 0, -- Icon in Topbar. Can use Lucide Icons (string) or Roblox Image (number). 0 to use no icon (default).
   LoadingTitle = "Azu-re Latch",
   LoadingSubtitle = "by JOKZ",
   Theme = "Default", -- Check https://docs.sirius.menu/rayfield/configuration/themes

   ToggleUIKeybind = "Z", -- The keybind to toggle the UI visibility (string like "K" or Enum.KeyCode)

   Discord = {
      Enabled = false, -- Prompt the user to join your Discord server if their executor supports it
      Invite = "QTzj2rtEDu", -- The Discord invite code, do not include discord.gg/. E.g. discord.gg/ ABCD would be ABCD
      RememberJoins = false -- Set this to false to make them join the discord every time they load it up
   },

   KeySystem = false, -- Set this to true to use our key system
   KeySettings = {
      Title = "Skibidi Pomni",
      Subtitle = "Key System",
      Note = "No method of obtaining the key is provided", -- Use this to tell the user how to get a key
      FileName = "SBO", -- It is recommended to use something unique as other scripts using Rayfield may overwrite your key file
      SaveKey = false, -- The user's key will be saved, but if you change the key, they will be unable to use your script
      GrabKeyFromSite = false, -- If this is true, set Key below to the RAW site you would like Rayfield to get the key from
      Key = {"OOLZ_92AL", "OLZIAYU_28171"} -- List of keys that will be accepted by the system, can be RAW file links (pastebin, github etc) or simple strings ("hello","key22")
   }
})

local Tab = Window:CreateTab("Dupe", 4483362458) -- Title, Image

local Button = Tab:CreateButton({
   Name = "DUPE",
   Callback = function()
   -- Script generated by SimpleSpy - credits to exx#9394

local args = {
	buffer.fromstring("\017\005\000music\001"),
	{
		"\192"
	}
}
game:GetService("ReplicatedStorage"):WaitForChild("ByteNetReliable"):FireServer(unpack(args))


   end,
})

local Button = Tab:CreateButton({
   Name = "Disable DUPE",
   Callback = function()
   -- Script generated by SimpleSpy - credits to exx#9394

local args = {
	buffer.fromstring("\017\005\000music\001"),
	{
		false
	}
}
game:GetService("ReplicatedStorage"):WaitForChild("ByteNetReliable"):FireServer(unpack(args))


   end,
})


local Button = Tab:CreateButton({
   Name = "Rejoin",
   Callback = function()
game:GetService("TeleportService"):Teleport(game.PlaceId, game.Players.LocalPlayer)
   end,
})
